### ISSUE TITLE
Error: Local Image

### ISSUE THREAD

**Issue by TheProdigyLeague** [NotAProton/trapwire#3]
The daemon is unable to find your image @NotAProton 

```
Error: 403
```

![dockerTrapWire](https://github.com/user-attachments/assets/c810ab6f-6bd4-4b41-8f88-4096b7e62fbd)

**Comment by NotAProton** [comment]
try this

```
docker run -p 3000:3000 -e MYSQL_USER=user -e MYSQL_PASSWORD=password -e AUTH=your_password -e TOKEN=hello ghcr.io/notaproton/trapwire
```

**Comment by TheProdigyLeague** [comment]
> try this
> 
> ```
> docker run -p 3000:3000 -e MYSQL_USER=user -e MYSQL_PASSWORD=password -e AUTH=your_password -e TOKEN=hello ghcr.io/notaproton/trapwire
> ```
```
Chromebook Version 93.0.4577.107 (Official Build) (64-bit)
```

![errorNoMariaDB](https://github.com/user-attachments/assets/44cb6719-373e-4f3f-af4c-1133e98749b7)

```bash
docker pull ghcr.io/notaproton/trapwire:sha256-26d2ca5ccc27d31be832c0daa7f6f5ff87ae86e4b0523686edcb9a7b66b0ece8.sig
sha256-26d2ca5ccc27d31be832c0daa7f6f5ff87ae86e4b0523686edcb9a7b66b0ece8.sig: Pulling from notaproton/trapwire
unsupported media type application/vnd.dev.cosign.simplesigning.v1+json
```

Closing this is not planned.
